### ISSUE TITLE
TODO機能作成

### ISSUE THREAD

**Issue by BuntinJP** [team-shinoto/FBS.js#12]

**Comment by BuntinJP** [comment]
2022/11/30
ブランチmainとの競合を解決。

**Comment by BuntinJP** [comment]
todo.jsonをモジュール最上部へ配置すること、todo.jsonのチェックは行えるが、その問題を解決することはユーザーがエディタを利用することを前提としている。

**Comment by RUNFUNRUN** [comment]
一度、メインにマージ

todoを消すコマンドは未完成

**Comment by BuntinJP** [comment]
とりあえずmainとのマージ、プルリク完了。
