### ISSUE TITLE
リンク呼び出し機能

### ISSUE THREAD

**Issue by RUNFUNRUN** [team-shinoto/FBS.js#25]
シラバス等を登録するコマンドを作成

**Comment by takataka427** [comment]
作成したチャンネルのIDを自動で変数に格納する方法がわからない

**Comment by takataka427** [comment]
urlを判別する機能をつくる

**Comment by takataka427** [comment]
url_register関数で
コマンド/url_register (name) (url)でurlをnameで保存する機能を作った

**Comment by takataka427** [comment]
url_open関数で
コマンド/url_open (name)でnameで登録したurlをbotが呼び出す機能を作った。

**Comment by takataka427** [comment]
url_register関数に
nameArray配列でnameを格納し、
urlArray配列でurlを格納する変数を用意した。
